language: node_js
os:
  - windows
  - linux
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: KDc98DmV42tI+6yKbD1kpxKQip3Pt36ea052fwNsVto7I2PtklK0BQc+qqs3LKnA9JEl7V+8OORGlbzs4427Hnyn0s+G/bIFOWAGX3M5O2ZooPYhw385G300Rv8H4FfT8rPm5JP6fplTLcfkEyouVj+swLU6qsBNLOnlED8Gz311NMPPIOzOxgQ3BLPa2opBVeU2ovpRuxNdGWgc5APshZCEycxWaHAAfwGxIQrl0muPbRaghw5lxhyB5grf98xc3uHUST4s3n+VnzIWTLAwC3k4xQwJ1Xyr6m9UqMJzrdYGGS6oZ9nSFEk74qM1EpdOdZSgSZJ36g92EwaovtFkQwkf4HYnn/WrukBP5v6htBl1+kI2wxsYKVYro2b+WA5HzgYn1utQZklBhUGtnNe9X2PJzXNbQRm9f2K25S2A0fvouEyFhTh7/4ebenvHavhJ3ioxfIqdzzAQXStPzXJqotAbNXbfivpVrwS8eD53XMXddOEcRBpHlIanooQeU9nv7awI+xuWs1tqF5ZZuUn9UOJmQmclPo0n9LXMouLEG1hUlowJ0YlOvTqkZaJkDR1jCtheN6EoEocOaKaoxx9SXcoLhmxDF55kuSz8wOhjQ9Ks0lt4f1zXSUZmttwyNK1ATM2/w0X+ZEO7TLS9wZ9dBhN8+7aZLvmImyCupjs8jsA=
  file:
    - 'vfile-statistics.js'
    - 'vfile-statistics.min.js'
  on:
    tags: true
